name: vixmo_new
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  google_sign_in: ^5.3.3
  stacked_firebase_auth: ^0.2.14
  stacked: ^2.3.12
  stacked_services: ^0.9.1
  percent_indicator: ^4.2.2
  shimmer: ^2.0.0
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  fl_chart: ^0.55.0
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.2
  google_fonts: ^3.0.1
  rflutter_alert: ^2.0.4
  google_maps_flutter: ^2.1.8
  flutter_map: ^1.1.1
  flutter_login_facebook: ^1.5.0+1
  flutter_facebook_auth: ^4.3.4+2
  babylonjs_viewer: ^1.1.4
  firebase_auth_oauth: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/icons/icons_bottom_home/grey/home_grey.png
    - assets/icons/icons_bottom_home/grey/battery_grey.png
    - assets/icons/icons_bottom_home/grey/setting_grey.png
    - assets/icons/icons_bottom_home/grey/camera_grey.png
    - assets/icons/icons_bottom_home/grey/map_grey.png

    - assets/icons/icons_bottom_home/blue/home_blue.png
    - assets/icons/icons_bottom_home/blue/battery_blue.png
    - assets/icons/icons_bottom_home/blue/setting_blue.png
    - assets/icons/icons_bottom_home/blue/camera_blue.png
    - assets/icons/icons_bottom_home/blue/map_blue.png

    - assets/3d/car_jeep.glb

    - assets/images/car.png
    - assets/images/car_battery.png
    - assets/images/car_battery.gif
    - assets/images/tes1.png
    - assets/images/tes2.png
    - assets/images/started_logo.png
    - assets/images/started_logo1.png
    - assets/images/started_logo2.png
    - assets/images/logo_fix.png
    - assets/images/zero_hd1.png
    - assets/images/monokrom.png
    - assets/images/car_new.png
    - assets/images/car_new_flare.png
    - assets/images/banner_warning.png
    - assets/images/zero_hd.png
    - assets/images/get_started.png
    - assets/images/get_started.png
    - assets/images/half_car.png
    - assets/images/half_car2.png
    - assets/images/half_car3.png
    - assets/images/half_car4.png
    - assets/images/half_car5.png
    - assets/images/half_car6.png
    - assets/images/half_car7.png
    - assets/images/half_car8.png
    - assets/images/half_car9.png
    - assets/images/logo.png
    - assets/images/image_login.png
    - assets/images/image_login2.png
    - assets/images/image_login3.png
    - assets/images/car_charge.png
    - assets/images/zero.png
    - assets/images/zero_fix.png
    - assets/images/zero_fix_new.png
    - assets/images/zero_front.png
    - assets/images/zero_tes.png
    - assets/images/vixmo_logo.png



    - assets/images/cam/rear_cam.jpg





    - assets/icons/ac.png
    - assets/icons/key.png
    - assets/icons/lock1.png
    - assets/icons/location.png
    - assets/icons/location_salin.png
    - assets/icons/charging.png
    - assets/icons/music.png
    - assets/icons/setting.png
    - assets/icons/right_arrow.png
    - assets/icons/left_arrow.png
    - assets/icons/left_arrow_fix.png

    - assets/icons/fuel.png
    - assets/icons/drive.png
    - assets/icons/lamp_on.png
    - assets/icons/home.png
    - assets/icons/drag.png
    - assets/icons/google_icon.png
    - assets/icons/facebook_icon.png
    - assets/icons/apple_icon.png
    - assets/icons/apple_icon_new.png
    - assets/icons/microsoft_icon.png
    - assets/icons/microsoft_icon_new.png

    - assets/icons/lock.png
    - assets/icons/lights.png
    - assets/icons/safety.png
    - assets/icons/appereance.png
    - assets/icons/account.png
    - assets/icons/control_panel.png
    - assets/icons/software.png
    - assets/icons/network.png
    - assets/icons/bluetooth.png
    - assets/icons/location_bottom.png


    - assets/icons/setting.png
    - assets/icons/icons_home/ac.png

    - assets/icons/icons_home/ac24.png
    - assets/icons/icons_home/est_range.png
    - assets/icons/icons_home/license.png
    - assets/icons/icons_home/lamp24.png
    - assets/icons/icons_home/lock24.png
    - assets/icons/icons_home/trunk24.png
    - assets/icons/icons_home/sn.png



    - assets/icons/icons_setting/appereance_setting.png
    - assets/icons/icons_setting/light_setting.png
    - assets/icons/icons_setting/lock_setting.png
    - assets/icons/icons_setting/warning_setting.png


    - assets/icons/icons_home/arrow_left.png


    - assets/icons/icons_home/menu_new/ac24_grey.png
    - assets/icons/icons_home/menu_new/lamp24_grey.png
    - assets/icons/icons_home/menu_new/lock24_grey.png
    - assets/icons/icons_home/menu_new/unlock24_grey.png
    - assets/icons/icons_home/menu_new/trunk24_grey.png

    - assets/icons/icons_home/menu_new/music24_grey.png
    - assets/icons/icons_home/menu_new/volume24_grey.png
    - assets/icons/icons_home/menu_new/mirror24_grey.png
    -
    -
    - assets/icons/icons_home/menu_new/ac24_blue.png
    - assets/icons/icons_home/menu_new/lamp24_blue.png
    - assets/icons/icons_home/menu_new/lock24_blue.png
    - assets/icons/icons_home/menu_new/trunk24_blue.png

    - assets/icons/icons_notif/warning_notif.png





    - assets/icons/icons_home/battery_new.png
    - assets/icons/icons_home/battery_new_only.png
    - assets/icons/icons_home/bell.png
    - assets/icons/icons_home/apps.png
    - assets/icons/icons_home/warning.png
    - assets/icons/icons_home/lock_new.png
    - assets/icons/icons_home/ac_new.png
    - assets/icons/icons_home/trunk_new.png
    - assets/icons/icons_home/lamp_new.png
    - assets/icons/icons_home/app.png
    - assets/icons/icons_home/charging.png
    - assets/icons/icons_home/frunk.png
    - assets/icons/icons_home/music.png
    - assets/icons/icons_home/phone.png
    - assets/icons/icons_home/trunk.png
    - assets/icons/icons_home/trunk_front_new.png
    - assets/icons/icons_home/volume.png
    - assets/icons/icons_home/mirror.png
    - assets/icons/icons_home/lock.png
    - assets/icons/icons_home/window.png
    - assets/icons/icons_home/go.png
    - assets/icons/icons_home/window_new.png
    - assets/icons/icons_home/charging_new.png
    - assets/icons/icons_home/lock2.png
    - assets/icons/icons_home/frunk2.png
    - assets/icons/icons_home/window2.png
    - assets/icons/icons_home/more.png
    - assets/icons/icons_home/mirror.png
    - assets/icons/icons_home/write.png
    - assets/icons/icons_home/line_indicator.png
    - assets/icons/icons_home/sein.png
    - assets/icons/icons_home/parking.png
    - assets/icons/icons_home/parking_black.png
    - assets/icons/icons_home/parking_grey.png
    - assets/icons/icons_home/trunk_front.png
    - assets/icons/icons_home/ac_front.png
    - assets/icons/icons_home/lock_front.png
    - assets/icons/icons_home/lamp_front.png


    - assets/icons/icons_camera/change_camera.png
    - assets/icons/icons_camera/left_view.png
    - assets/icons/icons_camera/right_view.png


    - assets/imgs/source_pin.png
    - assets/imgs/source_pin_android.png
    - assets/imgs/destination_pin.png
    - assets/imgs/car_icon.png
    - assets/imgs/src_pin.png
    - assets/imgs/car_pin.png
    - assets/imgs/dest_pin.png
    - assets/imgs/me.jpg
    - assets/imgs/farmer.jpeg
    - assets/imgs/marker_car.png
    - assets/imgs/marker_src.png
    - assets/imgs/aldo.jpeg
    - assets/imgs/marker_blue.png
    - assets/imgs/car_marker_fix.png

    - assets/icons/icons/bold/lights.png
    - assets/icons/icons/bold/lock.png
    - assets/icons/icons/bold/appereance.png
    - assets/icons/icons/bold/safety.png
    - assets/icons/icons/bold/account.png

    - assets/icons/icons_more/group_icon.png
    - assets/icons/icons_more/list_icon.png





  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SFUIDisplay-Ultralight.ttf
          weight: 100
        - asset: assets/fonts/SFUIDisplay-Thin.ttf
          weight: 200
        - asset: assets/fonts/SFUIDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFUIDisplay-Black.ttf
          weight: 900

    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.OTF
          weight: 700
        - asset: assets/fonts/SFProDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Heavy.ttf
          weight: 800

  #    - family: SF Pro Display Regular
  #      fonts:
  #        - asset: assets/fonts/SFProDisplay-Regular.ttf
  #        asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
